# Generated by Django 4.0.6 on 2022-07-06 17:10

import django.core.validators
from django.db import migrations, models
import seats.models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_alter_screeningdate_screening_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=seats.models.upload_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
