# Generated by Django 4.0.6 on 2022-07-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0004_cinemahall_remove_seat_seat_empty_seat_row_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row_number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='screening_date',
        ),
    ]
